# Generated by Django 5.0.2 on 2024-02-08 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliverers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverer',
            options={'verbose_name': 'Доставщик', 'verbose_name_plural': 'Доставщики'},
        ),
    ]
