# Generated by Django 5.0.2 on 2024-02-08 14:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliverers', '0002_alter_deliverer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('card', 'Карточка'), ('cash', 'Наличка'), ('transer', 'Перевод')], max_length=255, verbose_name='Вид платежа')),
                ('total_price', models.IntegerField(default=0, verbose_name='Общая сумма')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано')),
                ('status', models.CharField(choices=[('processing', 'Обрабатывается'), ('at work', 'В работе'), ('On the way', 'В пути'), ('Completed', 'Выполнен')], max_length=255, verbose_name='Статус')),
                ('deliverer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deliverers.deliverer', verbose_name='Доставщик')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.payment', verbose_name='Вид платежа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
