# Generated by Django 5.0.2 on 2024-02-08 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Заказаный товар', 'verbose_name_plural': 'Заказаные товары'},
        ),
    ]
