# Generated by Django 5.0.2 on 2024-02-09 15:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='structure',
            field=ckeditor.fields.RichTextField(verbose_name='Состав'),
        ),
    ]
